### ISSUE TITLE
 DAOrayaki  Bounty | Task |  Alpha Bonds: Risk-adjusted Bonding Curves for Financing Impact

### ISSUE THREAD

**Issue by Will-Holden** [DAOrayaki/DAOrayaki-Bounty#102]
Title: DAOrayaki  Bounty | Task |  Alpha Bonds: Risk-adjusted Bonding Curves for Financing Impact
类型: Translation
截止日期: 3/14/2022-3/16/2022
委员会审核: 3/17/2022-3/19/2022
要求:英译中； 3/14/2022-3/16/2022为创作者翻译时间，即创作者需要在3/16/2022号之前提交； 3/17/2022 -3/19/2022为委员会审核及投票时间。
链接: https://medium.com/block-science/alpha-bonds-risk-adjusted-bonding-curves-for-financing-impact-5be949fbc5a0
赏金: 100USDC + 20YakID(社区call)

Title: DAOrayaki  Bounty | Task |  Alpha Bonds: Risk-adjusted Bonding Curves for Financing Impact
Type: Translation
Deadline: 3/14/2022-3/16/2022
Committee Decision: 3/17/2022-3/19/2022
Description: English to Chinese;3/14/2022-3/16/2022 is the creator's translation time, that is, creators need to submit before 3/16 ;3/17/2022-3/19/2022 is the committee review and voting time.
Link: https://medium.com/block-science/alpha-bonds-risk-adjusted-bonding-curves-for-financing-impact-5be949fbc5a0
Bounty: 100USDC + 20 YakID (Community Call Discussion)

**Comment by ShaunTime** [comment]
Shaun will do this Bounty.
