### ISSUE TITLE
 DAOrayaki  Bounty | Task |  QT/ Scientists capture the fleeting dance of moiré excitons

### ISSUE THREAD

**Issue by Will-Holden** [DAOrayaki/DAOrayaki-Bounty#109]
Title: DAOrayaki  Bounty | Task |  QT/ Scientists capture the fleeting dance of moiré excitons
类型: Translation
截止日期: 3/15/2022-3/17/2022
委员会审核: 3/18/2022-3/20/2022
要求:英译中； 3/15/2022-3/17/2022为创作者翻译时间，即创作者需要在3/17/2022号之前提交； 3/18/2022 -3/20/2022为委员会审核及投票时间。
链接:https://medium.com/paradigm-fund/qt-scientists-capture-the-fleeting-dance-of-moiré-excitons-c532b25df355
赏金: 140USDC

Title: DAOrayaki  Bounty | Task |  QT/ Scientists capture the fleeting dance of moiré excitons
Type: Translation
Deadline: 3/15/2022-3/17/2022
Committee Decision: 3/18/2022-3/20/2022
Description: English to Chinese;3/15/2022-3/17/2022 is the creator's translation time, that is, creators need to submit before 3/17 ;3/18/2022-3/20/2022 is the committee review and voting time.
Link:https://medium.com/paradigm-fund/qt-scientists-capture-the-fleeting-dance-of-moiré-excitons-c532b25df355
Bounty: 140USDC

**Comment by tw23** [comment]
Shaytan#0977 will do this bounty
