### ISSUE TITLE
Batch Deposits for [op/zk] rollup / mixers / MACI  

### ISSUE THREAD

**Issue by Will-Holden** [DAOrayaki/DAOrayaki-Bounty#11]
**类型** : Translation
**时间**:  4天内
**要求**: 
- 将链接中的英文文章翻译为中文。
- 这是一个论坛帖子，翻译正文；
- 对于下面的讨论部分，选取有用的内容做一个总结或者在正文讨论的地方做一个植入.

**链接**: https://ethresear.ch/t/batch-deposits-for-op-zk-rollup-mixers-maci/6883
**Bounty** : 120 U

**Type**: Translation
**Deadline**: Within 4 days
**Requirement**: 
- Translate the English article in the link into Chinese.
- This is a forum post, translate the main content;
- For the following discussion part, select useful content to summarize or implant in the main content discussion place.

**Link**: https://ethresear.ch/t/batch-deposits-for-op-zk-rollup-mixers-maci/6883
**Bounty**: 120 U

**Comment by helloDoraHacks** [comment]
@ZWL8 please register your wallet account address at [HackerLink](https://github.com/login/oauth/authorize?client_id=51f55800df57929f5348&redirect_uri=https%3A//hackerlink.io/bounty/47%23ZWL8&scope=) to get bounty bonus!
