### ISSUE TITLE
MACI anonymization - using rerandomizable encryption 

### ISSUE THREAD

**Issue by Will-Holden** [DAOrayaki/DAOrayaki-Bounty#13]
**类型** : Translation
**时间**: 4天内
**要求**: 将链接中的英文文章翻译为中文。
**链接**: https://ethresear.ch/t/maci-anonymization-using-rerandomizable-encryption/7054
**Bounty** : 100 U

**Type**: Translation
**Deadline**: Within 4 days
**Requirement**: Translate the English article in the link into Chinese.
**Link**: https://ethresear.ch/t/maci-anonymization-using-rerandomizable-encryption/7054
**Bounty**: 100 U

**Comment by web3Zhaoxinlong** [comment]
just translate and open PR here is ok?
