### ISSUE TITLE
 DAOrayaki  Bounty | Task |  Try Out the Latest Advances in Quantum Computing With Prototypes

### ISSUE THREAD

**Issue by Will-Holden** [DAOrayaki/DAOrayaki-Bounty#133]
**Title**: DAOrayaki  Bounty | Task |  Try Out the Latest Advances in Quantum Computing With Prototypes
**截止日期**: 3/24/2022
**type**:translation
**委员会审核**: 3/25/2022-3/27/2022
**要求**:英译中；-为创作者翻译时间，即创作者需要在号之前提交； 3/25/2022 -3/27/2022为委员会审核及投票时间。
**链接**:https://medium.com/qiskit/try-out-the-latest-advances-in-quantum-computing-with-ibm-quantum-prototypes-11f51124cb61
**赏金**: 40u

**Title**: DAOrayaki  Bounty | Task |  Try Out the Latest Advances in Quantum Computing With Prototypes
**Deadline**: 3/24/2022
**type**:translation
**Committee Decision**: 3/25/2022-3/27/2022
**Description**: English to Chinese;3/22/2022-3/24/2022 is the creator's translation time, that is, creators need to submit before 3/24 ;3/25/2022-3/27/2022 is the committee review and voting time.
**Link**:https://medium.com/qiskit/try-out-the-latest-advances-in-quantum-computing-with-ibm-quantum-prototypes-11f51124cb61
**Bounty**: 40u

**Comment by hahaho1** [comment]
hahaho will do this bounty.
