### ISSUE TITLE
 DAOrayaki  Bounty | Task |  Why This Quantum Pioneer Thinks We Need More People Working on Quantum Algorithms

### ISSUE THREAD

**Issue by Will-Holden** [DAOrayaki/DAOrayaki-Bounty#134]
**Title**: DAOrayaki  Bounty | Task |  Why This Quantum Pioneer Thinks We Need More People Working on Quantum Algorithms
**截止日期**: 3/24/2022
**type**:translation
**委员会审核**: 3/25/2022-3/27/2022
**要求**:英译中；-为创作者翻译时间，即创作者需要在号之前提交； 3/25/2022 -3/27/2022为委员会审核及投票时间。
**链接**: https://medium.com/qiskit/why-this-quantum-pioneer-thinks-we-need-more-people-working-on-quantum-algorithms-3020729c61e1
**赏金**: 50u

**Title**: DAOrayaki  Bounty | Task |  Why This Quantum Pioneer Thinks We Need More People Working on Quantum Algorithms
**Deadline**: 3/24/2022
**type**:translation
**Committee Decision**: 3/25/2022-3/27/2022
**Description**: English to Chinese;3/22/2022-3/24/2022 is the creator's translation time, that is, creators need to submit before 3/24 ;3/25/2022-3/27/2022 is the committee review and voting time.
**Link**: https://medium.com/qiskit/why-this-quantum-pioneer-thinks-we-need-more-people-working-on-quantum-algorithms-3020729c61e1
**Bounty**: 50u

**Comment by tw23** [comment]
Shaytan#0977 will do this bounty
