### ISSUE TITLE
 DAOrayaki  Bounty | Task |  Music NFTs Become Latest Battleground Between Capitalists and Creators

### ISSUE THREAD

**Issue by Will-Holden** [DAOrayaki/DAOrayaki-Bounty#146]
**Title**: DAOrayaki  Bounty | Task |  Music NFTs Become Latest Battleground Between Capitalists and Creators
**类型**: Translation
**截止日期**: 3/30/2022-3/31/2022
**委员会审核**: 4/01/2022-4/02/2022
**要求**:英译中； 3/30/2022-3/31/2022为创作者翻译时间，即创作者需要在3/31/2022号之前提交； 4/01/2022 -4/02/2022为委员会审核及投票时间。
**链接**: https://www.decential.io/features/x8j8cea0ar9wjt4x1106a78p8cur5t
**赏金**: 80u

**Title**: DAOrayaki  Bounty | Task |  Music NFTs Become Latest Battleground Between Capitalists and Creators
**Type**: Translation
**Deadline**: 3/30/2022-3/31/2022
**Committee Decision**: 4/01/2022-4/02/2022
**Description**: English to Chinese; 3/30/2022-3/31/2022 is the creator's translation time ; 4/01/2022-4/02/2022   is the committee review and voting time.
**Link**: https://www.decential.io/features/x8j8cea0ar9wjt4x1106a78p8cur5t
**Bounty**: 80u

**Comment by hahaho1** [comment]
hahaho will do this bounty.
