### ISSUE TITLE
 DAOrayaki  Bounty | Task |  The State of Decentralized Applications (dApps) — H2 2021 Review

### ISSUE THREAD

**Issue by Will-Holden** [DAOrayaki/DAOrayaki-Bounty#147]
**Title**: DAOrayaki  Bounty | Task |  The State of Decentralized Applications (dApps) — H2 2021 Review
**类型**: Translation
**截止日期**: 3/30/2022-3/31/2022
**委员会审核**: 4/01/2022-4/02/2022
**要求**:英译中； 3/30/2022-3/31/2022为创作者翻译时间，即创作者需要在3/31/2022号之前提交； 4/01/2022 -4/02/2022为委员会审核及投票时间。
**链接**: https://kyleellicott.medium.com/the-state-of-decentralized-applications-dapps-h2-2021-review-d645131ae783
**赏金**: 60u

**Title**: DAOrayaki  Bounty | Task |  The State of Decentralized Applications (dApps) — H2 2021 Review
**Type**: Translation
**Deadline**: 3/30/2022-3/31/2022
**Committee Decision**: 4/01/2022-4/02/2022
**Description**: English to Chinese; 3/30/2022-3/31/2022  is the creator's translation time; 4/01/2022-4/02/2022  is the committee review and voting time.
**Link**: https://kyleellicott.medium.com/the-state-of-decentralized-applications-dapps-h2-2021-review-d645131ae783
**Bounty**: 60u

**Comment by hahaho1** [comment]
hahaho will do this bounty.
