### ISSUE TITLE
 DAOrayaki  Bounty | Task |  Pricing Tokens in a Web3 Economy

### ISSUE THREAD

**Issue by Will-Holden** [DAOrayaki/DAOrayaki-Bounty#148]
**Title**: DAOrayaki  Bounty | Task |  Pricing Tokens in a Web3 Economy
**类型**: Translation
**截止日期**: 3/30/2022-3/31/2022
**委员会审核**: 4/01/2022-4/02/2022
**要求**:英译中； 3/30/2022-3/31/2022为创作者翻译时间，即创作者需要在3/31/2022号之前提交； 4/01/2022 -4/02/2022为委员会审核及投票时间。
**链接**: https://medium.datadriveninvestor.com/pricing-tokens-in-a-web3-economy-1a37184edf37
**赏金**: 40u

**Title**: DAOrayaki  Bounty | Task |  Pricing Tokens in a Web3 Economy
**Type**: Translation
**Deadline**: 3/30/2022-3/31/2022
**Committee Decision**: 4/01/2022-4/02/2022
**Description**: English to Chinese; 3/30/2022-3/31/2022  is the creator's translation time; 4/01/2022-4/02/2022   is the committee review and voting time.
**Link**: https://medium.datadriveninvestor.com/pricing-tokens-in-a-web3-economy-1a37184edf37
**Bounty**: 40u

**Comment by ShaunTime** [comment]
Shaun#9454 will do this bounty.
