### ISSUE TITLE
 DAOrayaki  Bounty | Task |  Banking competition is heating up in the metaverse — What is the difference between Open Banking and Open Finance? DeFi super app?

### ISSUE THREAD

**Issue by Will-Holden** [DAOrayaki/DAOrayaki-Bounty#149]
**Title**: DAOrayaki  Bounty | Task |  Banking competition is heating up in the metaverse — What is the difference between Open Banking and Open Finance? DeFi super app?
**类型**: Translation
**截止日期**: 3/30/2022-3/31/2022
**委员会审核**: 4/01/2022-4/02/2022
**要求**:英译中； 3/30/2022-3/31/2022为创作者翻译时间，即创作者需要在3/31/2022号之前提交； 4/01/2022 -4/02/2022为委员会审核及投票时间。
**链接**: https://medium.com/the-capital/banking-competition-is-heating-up-in-the-metaverse-what-is-the-difference-between-open-banking-and-b1fbcf7f7a25
**赏金**: 60u

**Title**: DAOrayaki  Bounty | Task |  Banking competition is heating up in the metaverse — What is the difference between Open Banking and Open Finance? DeFi super app?
**Type**: Translation
**Deadline**: 3/30/2022-3/31/2022
**Committee Decision**: 4/01/2022-4/02/2022
**Description**: English to Chinese; 3/30/2022-3/31/2022  is the creator's translation time; 4/01/2022-4/02/2022   is the committee review and voting time.
**Link**: https://medium.com/the-capital/banking-competition-is-heating-up-in-the-metaverse-what-is-the-difference-between-open-banking-and-b1fbcf7f7a25
**Bounty**: 60u

**Comment by hahaho1** [comment]
hahaho will do this bounty.
