### ISSUE TITLE
 DAOrayaki  Bounty | Task |  HAUS Party LIVE — Scaling Values in a Growth First Economy🎉!

### ISSUE THREAD

**Issue by Will-Holden** [DAOrayaki/DAOrayaki-Bounty#151]
**Title**: DAOrayaki  Bounty | Task |  HAUS Party LIVE — Scaling Values in a Growth First Economy🎉!
**类型**: Translation
**截止日期**: 3/30/2022-3/31/2022
**委员会审核**: 4/01/2022-4/02/2022
**要求**:英译中； 3/30/2022-3/31/2022为创作者翻译时间，即创作者需要在3/31/2022号之前提交； 4/01/2022 -4/02/2022为委员会审核及投票时间。
**链接**: https://medium.com/daohaus-club/haus-party-live-transcription-9eaf022fd890
**赏金**: 50u

**Title**: DAOrayaki  Bounty | Task |  HAUS Party LIVE — Scaling Values in a Growth First Economy🎉!
**Type**: Translation
**Deadline**: 3/30/2022-3/31/2022
**Committee Decision**: 4/01/2022-4/02/2022
**Description**: English to Chinese; 3/30/2022-3/31/2022  is the creator's translation time ; 4/01/2022-4/02/2022   is the committee review and voting time.
**Link**: https://medium.com/daohaus-club/haus-party-live-transcription-9eaf022fd890
**Bounty**: 50u

**Comment by xinyang309** [comment]
xinyang309 will do the bounty.
