### ISSUE TITLE
 DAOrayaki  Bounty | Task |  Crypto’s emergence as a geopolitical force

### ISSUE THREAD

**Issue by Will-Holden** [DAOrayaki/DAOrayaki-Bounty#152]
**Title**: DAOrayaki  Bounty | Task |  Crypto’s emergence as a geopolitical force
**类型**: Translation
**截止日期**: 3/30/2022-3/31/2022
**委员会审核**: 4/01/2022-4/02/2022
**要求**:英译中； 3/30/2022-3/31/2022为创作者翻译时间，即创作者需要在3/31/2022号之前提交； 4/01/2022 -4/02/2022为委员会审核及投票时间。
**链接**: https://blog.coinbase.com/cryptos-emergence-as-a-geopolitical-force-30f29d62e562
**赏金**: 50u

**Title**: DAOrayaki  Bounty | Task |  Crypto’s emergence as a geopolitical force
**Type**: Translation
**Deadline**: 3/30/2022-3/31/2022
**Committee Decision**: 4/01/2022-4/02/2022
**Description**: English to Chinese; 3/30/2022-3/31/2022  is the creator's translation time ; 4/01/2022-4/02/2022    is the committee review and voting time.
**Link**: https://blog.coinbase.com/cryptos-emergence-as-a-geopolitical-force-30f29d62e562
**Bounty**: 50u

**Comment by ShaunTime** [comment]
Shaun#9454 will do this bounty.

**Comment by Leosiiii** [comment]
0xAA637299c193f8Ae769ee58e113030C1199625bC
