### ISSUE TITLE
DAOrayaki Bounty | Task | Copyright Vulnerabilities in NFTs

### ISSUE THREAD

**Issue by asqwasweer** [DAOrayaki/DAOrayaki-Bounty#162]
Title: DAOrayaki | Copyright Vulnerabilities in NFTs
Deadline: 4/15/2022-4/17/2022 
Committee Decision: 4/17/2022-4/22/2022 
**Description: English to Chinese**;
4/15/2022-4/17/2022 is the creator's translation time;4/17/2022-4/22/2022 is the committee review and voting time. 
link: https://medium.com/initc3org/copyright-vulnerabilities-in-nfts-317e02d8ae26
Bounty: 110u

**Comment by ShaunTime** [comment]
Shaun#9454 Will do this bounty.
