### ISSUE TITLE
DAOrayaki Bounty | Task |Blockchain for Decentralized Identity — Social Impact

### ISSUE THREAD

**Issue by asqwasweer** [DAOrayaki/DAOrayaki-Bounty#165]
Title: DAOrayaki | Blockchain for Decentralized Identity — Social Impact
Deadline: 4/15/2022-4/17/2022 
Committee Decision: 4/18/2022-4/23/2022 
**Description: English to Chinese;**
4/15/2022-4/17/2022 is the creator's translation time, that is, creators need to submit before 4/17 ;4/18/2022-4/23/2022 is the committee review and voting time. 
link: https://rao-anita.medium.com/blockchain-for-decentralized-identity-social-impact-a561ac7e4b6
Bounty: 35u

**Comment by kingstenzzz** [comment]
kingsten#4934 will do the bounty.
