### ISSUE TITLE
DAOrayaki Bounty | Task |Coordination and Crypto Charity

### ISSUE THREAD

**Issue by asqwasweer** [DAOrayaki/DAOrayaki-Bounty#166]
Title: DAOrayaki | Coordination and Crypto Charity
Deadline: 4/15/2022-4/17/2022 
Committee Decision: 4/18/2022-4/23/2022 
**Description: English to Chinese;**
4/15/2022-4/17/2022 is the creator's translation time, that is, creators need to submit before 4/17; 4/18/2022-4/23/2022 is the committee review and voting time. 
link: https://medium.com/etherscan-blog/coordination-and-crypto-charity-b91ec4993a48
Bounty: 60u

**Comment by xinyang309** [comment]
xinyang309 will do the bounty.
