### ISSUE TITLE
DAOrayaki Bounty | Task |HAUS Party LIVE🎉 — Lorecrafting Beyond the DAO MMORPG!

### ISSUE THREAD

**Issue by asqwasweer** [DAOrayaki/DAOrayaki-Bounty#167]
Title: DAOrayaki | HAUS Party LIVE🎉 — Lorecrafting Beyond the DAO MMORPG!
Deadline: 4/15/2022-4/17/2022 
Committee Decision: 4/18/2022-4/23/2022 
**Description: English to Chinese;**
4/15/2022-4/17/2022 is the creator's translation time, that is, creators need to submit before 4/16 ;4/18/2022-4/23/2022 is the committee review and voting time. 
link: https://medium.com/daohaus-club/haus-party-live-lorecrafting-beyond-the-dao-mmorpg-7f845e42f026
Bounty: 50u

**Comment by kingstenzzz** [comment]
kingsten#4934 will do the bounty.
