### ISSUE TITLE
DAOrayaki Bounty | Task |17 Important Factors in Fundamental Analysis

### ISSUE THREAD

**Issue by asqwasweer** [DAOrayaki/DAOrayaki-Bounty#168]
Title: DAOrayaki | 17 Important Factors in Fundamental Analysis
Deadline: 4/15/2022-4/17/2022 
Committee Decision: 4/18/2022-4/23/2022 
**Description: English to Chinese;**
4/15/2022-4/17/2022 is the creator's translation time, that is, creators need to submit before 4/16 ;4/18/2022-4/23/2022 is the committee review and voting time. 
link: https://medium.com/coinmonks/17-important-factors-in-fundamental-analysis-9cb61c0ec940
Bounty: 60u

**Comment by hahaho1** [comment]
hahaho will do this bounty
