### ISSUE TITLE
DAOrayaki Bounty | Task |A Framework for Network Effects in Web3

### ISSUE THREAD

**Issue by asqwasweer** [DAOrayaki/DAOrayaki-Bounty#169]
Title: DAOrayaki | A Framework for Network Effects in Web3
Deadline: 4/15/2022-4/17/2022
Committee Decision: 4/18/2022-4/23/2022
**Description: English to Chinese;**
4/15/2022-4/17/2022 is the creator's translation time, that is, creators need to submit before 4/17 ;4/18/2022-4/23/2022 is the committee review and voting time.
link: https://medium.com/@soumilsinghnz/a-framework-for-network-effects-in-web3-d415b6652d0b
Bounty: 80u

**Comment by xinyang309** [comment]
xinyang309 will do the bounty.
