### ISSUE TITLE
DAOrayaki Bounty | Task |Rich in Data, Poor in Wisdom: Science Needs a Decentralized Data Commons

### ISSUE THREAD

**Issue by asqwasweer** [DAOrayaki/DAOrayaki-Bounty#170]
Title: DAOrayaki | Rich in Data, Poor in Wisdom: Science Needs a Decentralized Data Commons
Deadline: 4/15/2022-4/17/2022 
Committee Decision: 4/18/2022-4/23/2022 
**Description: English to Chinese;**
4/15/2022-4/17/2022 is the creator's translation time, that is, creators need to submit before 4/17 ;4/18/2022-4/23/2022 is the committee review and voting time. 
link: https://pulse.opsci.io/rich-in-data-poor-in-wisdom-science-needs-a-decentralized-data-commons-98c7ffdb56a1
Bounty: 60u

**Comment by ShaunTime** [comment]
Shaun#9454 Will do this bounty.
