### ISSUE TITLE
DAOrayaki Bounty | Task |Tokenomics Red Flags You Can’t Afford to Ignore (Part I)

### ISSUE THREAD

**Issue by asqwasweer** [DAOrayaki/DAOrayaki-Bounty#171]
Title: DAOrayaki |Tokenomics Red Flags You Can’t Afford to Ignore (Part I)
Deadline: 4/15/2022-4/17/2022 
Committee Decision: 4/18/2022-4/23/2022 
**Description: English to Chinese;**
4/15/2022-4/17/2022 is the creator's translation time, that is, creators need to submit before 4/17 ;4/18/2022-4/23/2022 is the committee review and voting time. 
link: https://medium.com/coinmonks/tokenomics-red-flags-you-cant-afford-to-ignore-part-i-1874f251c4db
Bounty: 60u

**Comment by hahaho1** [comment]
hahaho will do this bounty
