### ISSUE TITLE
DAOrayaki Bounty | Task |What is Membership in a DAO?

### ISSUE THREAD

**Issue by asqwasweer** [DAOrayaki/DAOrayaki-Bounty#184]
Title: DAOrayaki |What is Membership in a DAO?
 Deadline: 4/27/2022-4/30/2022  
Committee Decision: 5/1/2022-5/4/2022  
**Description: English to Chinese;**
4/27/2022-4/30/2022 is the creator's translation time, that is, creators need to submit before 4/30 ;5/1/2022-5/4/2022 is the committee review and voting time.  
link: https://gideonro.medium.com/dao-membership-4a213476057d
Bounty：40u

**Comment by ShaunTime** [comment]
Shaun#9454 will do this bounty.

**Comment by ShaunTime** [comment]
Closed #189

**Comment by jussu123** [comment]
什么是 DAO 中的成员资格????????

加入 DAO 即同意其工作方式
到了解人们如何加入去中心化自治组织 (DAO)，没有比“无许可”的想法更好的起点了。好的定义可以作为解锁理解的钥匙，我喜欢这个无需许可：

如果一个技术社会系统可以通过遵守公开规定的程序，在不需要当局许可的情况下参与该系统或基础设施的使用、开发和治理，则该系统被认为是无许可的。
[——凯尔西·纳本和迈克尔·扎格姆](https://policyreview.info/glossary/permissionlessness)

我认为[DAO](https://medium.com/p/32fcaaaae5f8)本质上是无需许可的。加入 DAO 并不是某人对您个人做出的招聘决定。正如 Nabben 和 Zargham 所说，这取决于你是否遵守“公开声明的程序”。这就是你如何成为 DAO 的组成部分——成员。

现实情况是，我们仍处于 DAO 成员资格的早期阶段。今天，大多数 DAO 入职程序都非常简单，通常归结为拥有一个代币。就像访问地铁系统一样，您只需出示代币即可进入。但是这种简单的代币门控访问 DAO 成员资格只是触及加入 DAO 的“遵守公共程序”可能看起来像的表面.

DAO 的膜
吨组织入职的未来比今天更具渗透性。与所有组织一样，DAO 具有将其内部操作与周围环境分开的边界。Nabben 和 Zargham[指出，](https://policyreview.info/glossary/permissionlessness)跨越未经许可的边界是任何人都可以在没有事先获得某些权威批准的情况下进行的事情。只要遵守公开声明的程序，你就可以了。

一般来说，当您模仿经过充分测试的自然设计时，您就知道自己正朝着正确的方向前进。无许可模仿了生活本身的基本组成部分。像 DAO 一样的生物细胞具有可渗透的边界——称为膜

什么是 DAO 中的成员资格????????

加入 DAO 即同意其工作方式
到了解人们如何加入去中心化自治组织 (DAO)，没有比“无许可”的想法更好的起点了。好的定义可以作为解锁理解的钥匙，我喜欢这个无需许可：

如果一个技术社会系统可以通过遵守公开规定的程序，在不需要当局许可的情况下参与该系统或基础设施的使用、开发和治理，则该系统被认为是无许可的。
[——凯尔西·纳本和迈克尔·扎格姆](https://policyreview.info/glossary/permissionlessness)

我认为[DAO](https://medium.com/p/32fcaaaae5f8)本质上是无需许可的。加入 DAO 并不是某人对您个人做出的招聘决定。正如 Nabben 和 Zargham 所说，这取决于你是否遵守“公开声明的程序”。这就是你如何成为 DAO 的组成部分——成员。

现实情况是，我们仍处于 DAO 成员资格的早期阶段。今天，大多数 DAO 入职程序都非常简单，通常归结为拥有一个代币。就像访问地铁系统一样，您只需出示代币即可进入。但是这种简单的代币门控访问 DAO 成员资格只是触及加入 DAO 的“遵守公共程序”可能看起来像的表面.

DAO 的膜
吨组织入职的未来比今天更具渗透性。与所有组织一样，DAO 具有将其内部操作与周围环境分开的边界。Nabben 和 Zargham[指出，](https://policyreview.info/glossary/permissionlessness)跨越未经许可的边界是任何人都可以在没有事先获得某些权威批准的情况下进行的事情。只要遵守公开声明的程序，你就可以了。

一般来说，当您模仿经过充分测试的自然设计时，您就知道自己正朝着正确的方向前进。无许可模仿了生活本身的基本组成部分。像 DAO 一样的生物细胞具有可渗透的边界——称为膜


细胞也类似于参与 DAO 的“使用、开发和治理”的“公开声明的程序”。在上图中，细胞的两层膜中嵌入了一类特殊的蛋白质，称为“[转运](https://www.wikiwand.com/en/Membrane_transport_protein)蛋白” 。这些蛋白质充当细胞内部和外部之间的桥梁。有许多类型的转运蛋白，每一种都旨在以非常特殊的方式在细胞膜上移动能量和物质。将每种类型的传输器视为参与单元的特定协议。

这就是细胞在保持对周围环境开放的同时保持边界的方式。该膜是未经许可的。没有外力指挥交通，细胞中没有人造人授权什么进入和不进入。事物只需遵守这些运输工具的“公开”暴露界面即可加入细胞。

因此，无许可的组织结构深入生活的编码。它是一种新兴的、[模块化](https://medium.com/p/df18c957c603)的协调设计。它也是真正大规模人类合作形式的关键——这种形式现在随着分散的自治组织而出现。

定义 DAO 成员资格
我们现在可以回到穿过这层膜并实际加入 DAO 意味着什么的问题。

成员资格在 DAO 环境中的定义不一致。对于一些人来说，仅仅加入 Discord 服务器就构成了一种会员资格，而对于另一些人来说，你需要一个可能花费数十万美元的不可替代代币。当然，每个 DAO 都应该可以自由地定义其成员资格。但是，是否有模式可以说明 DAO 成员的总体情况？

我相信 DAO 成员有一个普遍的叙述，它依赖于 Nabben 和 Zargham 提出的无许可概念。简单来说，成员资格归结为新成员同意遵守公开声明的参与 DAO 的程序。换句话说，成员资格是由成员达成的无许可协议的结果，以遵守使用、构建和管理 DAO 的协议。

DAO 成员资格和入职
吨他真正的问题是该无许可会员协议实际上是什么样的。今天的入职流程往往非常简单——通常是拥有一个代币，甚至只是同意 Discord 服务器上的社区条款和条件。但真正同意使用、构建和管理 DAO 的协议要比这复杂得多。DAO 是复杂的系统，部分是技术性的，部分是社会学的，甚至是部分生物学的。

遵守 DAO 的程序比遵守区块链协议的规则要微妙得多。要遵循这些复杂的社会技术系统的程序，成员需要首先了解它们。这意味着教育和入职培训过程对于新人同意 DAO 协议的能力是绝对必要的。如果在使用、构建和管理 DAO 的过程中没有这种理解和培训，那么坚持的想法就毫无意义——会员资格也是如此。

因此，DAO 入职与教育和入职培训过程有着错综复杂的联系。因为它们是未经许可的，所以这些教育和入职培训过程看起来[与传统公司的非常不同](https://medium.com/token-engineering-commons/the-permissionless-dao-32fcaaaae5f8)。没有人力资源部门把关招聘过程。任何想加入的人都可以加入——只要他们同意遵守协议。

DAO 中的成员开发
加入组织的这一新现实需要重新考虑教育和定位过程。DAO 需要为新成员定义可能采取社区契约形式的公共承诺。定义这些协议将意味着就所有 DAO 成员应共享以使用、贡献和管理组织的初始、基本级别的理解达成一致。随着时间的推移，随着成员责任的增加，这种理解必须加深。更大的责任需要更大的承诺来遵守 DAO 的协议。

在成员参与 DAO 的过程中，责任的扩大意味着从未真正完成入职。随着它从初始阶段开始，入职看起来越来越像正在进行的个人和职业发展。DAO 成员资格始于对入职协议的标准化和公开阐述，但随着时间的推移演变为越来越个性化的专业和个人发展之旅。在此过程的每一步，使用、构建和管理 DAO 的协议必须清晰、公开且无需许可。这并不容易——尤其是随着责任的加深和变得更加复杂。这是摆在我们面前的挑战。清晰的角色表达和社区声誉系统只是将成员入职和参与扩展到当今大多数 DAO 之外的一些关键。

作为控制论实体的 DAO
DAO 是一种新的技术巢穴，用于容纳人类社区和工作。入职流程根据 DAO 中编码的社区价值观调整个人使用、构建和管理这些系统的方式。这就是 DAO管理其社区的方式。它作为一种技术住房，因此 DAO 和社区作为一个半人半机器的控制论实体共同运作。

如果将新来者带入这样的控制论系统听起来很反乌托邦，那只是因为我们现有的尝试远远没有发挥其潜力。对于人类或地球而言，与机器合作的企业蓝图通常并不顺利。

DAO 成员资格和治理
DAO 通过将这些技术系统的治理牢牢掌握在社区成员手中，为改变这种伙伴关系创造了机会。使用和贡献于 DAO 都是重要的功能，但治理是定义这些系统的使命和操作参数的要素。治理有很大的权力，也有很大的责任

承担 DAO 治理责任的第一步必须从同意遵守其协议开始。为此，DAO 管理者需要首先了解这些协议。换句话说，他们需要方向，就像 DAO 的其他成员一样。事实上，州长更需要指导，因为他们的责任要大得多。

如果成员资格是通过同意遵守 DAO 的协议而产生的，并且管理者也有同样的要求，那么根据定义，如果不同时成为 DAO 成员，就不能真正成为 DAO 管理者。两者都需要遵守并理解底层协议。
