### ISSUE TITLE
DAOrayaki Bounty | Task |JPEG’d: Using Your NFT as Collateral

### ISSUE THREAD

**Issue by asqwasweer** [DAOrayaki/DAOrayaki-Bounty#187]
Title: DAOrayaki |JPEG’d: Using Your NFT as Collateral
 Deadline: 4/27/2022-4/30/2022  
Committee Decision: 5/1/2022-5/4/2022  
**Description: English to Chinese;**
4/27/2022-4/30/2022 is the creator's translation time, that is, creators need to submit before 4/30 ;5/1/2022-5/4/2022 is the committee review and voting time.  
link: https://medium.com/blockchain-at-usc/jpegd-using-your-nft-as-collateral-82a36df719a7
Bounty：55u

**Comment by kingstenzzz** [comment]
kingsten will do this bounty
