### ISSUE TITLE
DAOrayaki Bounty | Task |Decentralized credit scores: How can blockchain tech change ratings

### ISSUE THREAD

**Issue by asqwasweer** [DAOrayaki/DAOrayaki-Bounty#189]
Title: DAOrayaki |Decentralized credit scores: How can blockchain tech change ratings
 Deadline: 4/27/2022-4/30/2022  
Committee Decision: 5/1/2022-5/4/2022  
**Description: English to Chinese;**
4/27/2022-4/30/2022 is the creator's translation time, that is, creators need to submit before 4/30 ;5/1/2022-5/4/2022 is the committee review and voting time.  
link: https://cointelegraph.com/news/decentralized-credit-scores-how-can-blockchain-tech-change-ratings
Bounty：65u

**Comment by ShaunTime** [comment]
Shaun#9454 will do this bounty.
