### ISSUE TITLE
DAOrayaki Bounty | Task |QT/ First hybrid quantum bit based on topological insulators

### ISSUE THREAD

**Issue by asqwasweer** [DAOrayaki/DAOrayaki-Bounty#196]
Title: DAOrayaki | QT/ First hybrid quantum bit based on topological insulators
 Deadline: 5/12/2022  
Committee Decision: 5/13/2022-5/15/2022  
**Description: English to Chinese;** 
5/10/2022-5/12/2022 is the creator's translation time, that is, creators need to submit before 5/13 ;5/13/2022-5/15/2022 is the committee review and voting time.  
link: https://medium.com/paradigm-fund/qt-first-hybrid-quantum-bit-based-on-topological-insulators-33dc609b0020
Bounty：150u

**Comment by susu0929** [comment]
skyh#4923 will do this bounty

**Comment by xinyang309** [comment]
xinyang309 will to the bounty
