### ISSUE TITLE
DAOrayaki | Task|Space Situated Blockchain

### ISSUE THREAD

**Issue by asqwasweer** [DAOrayaki/DAOrayaki-Bounty#204]
Title: DAOrayaki | Space Situated Blockchain
 Deadline: 5/12/2022  
Committee Decision: 5/13/2022-5/15/2022  
Description: English to Chinese; 
5/10/2022-5/12/2022 is the creator's translation time, that is, creators need to submit before 5/13 ;5/13/2022-5/15/2022 is the committee review and voting time.  
link: https://enterlifeonline.medium.com/space-situated-blockchain-515773bb285d
Bounty：45u

**Comment by Emerie111** [comment]
will do this bounty

**Comment by Emerie111** [comment]
I will like to attempt this bounty

**Comment by susu0929** [comment]
OK




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月15日(星期天) 下午5:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DAOrayaki/DAOrayaki-Bounty] DAOrayaki | Task|Space Situated Blockchain (Issue #204)






会做这个赏金

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
你收到这个是因为你评论了。留言 ID ***@***.*** do this bounty.—

**Comment by susu0929** [comment]
OK




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月15日(星期天) 下午5:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DAOrayaki/DAOrayaki-Bounty] DAOrayaki | Task|Space Situated Blockchain (Issue #204)





 
I will like to attempt this bounty

**Comment by testDAO** [comment]
> I will like to attempt this bounty

hi, you need to join our discord server to take part in our bounties, https://discord.gg/G8BbYxpy
