### ISSUE TITLE
DAOrayaki | Task|Augmented Reality Meets Space Exploration

### ISSUE THREAD

**Issue by asqwasweer** [DAOrayaki/DAOrayaki-Bounty#205]
Title: DAOrayaki | Augmented Reality Meets Space Exploration
 Deadline: 5/12/2022  
Committee Decision: 5/13/2022-5/15/2022  
Description: English to Chinese; 
5/10/2022-5/12/2022 is the creator's translation time, that is, creators need to submit before 5/13 ;5/13/2022-5/15/2022 is the committee review and voting time.  
link: https://medium.com/@thirdeyegen/augmented-reality-meets-space-exploration-a27e3d65ec15
Bounty：45u

**Comment by wonderxxx** [comment]
wonderxxx will do this bounty.

**Comment by Heyyawn** [comment]
Heyyawn#1025 will do this bounty
