### ISSUE TITLE
DAOrayaki |task|Mapping the Computer-Aided Governance Process

### ISSUE THREAD

**Issue by asqwasweer** [DAOrayaki/DAOrayaki-Bounty#218]
Title: DAOrayaki | Mapping the Computer-Aided Governance Process
 Deadline: 5/21/2022  
Committee Decision: 5/22/2022-5/24/2022  
**Description: English to Chinese;** 
5/18/2022-5/21/2022 is the creator's translation time, that is, creators need to submit before 5/12 ;5/22/2022-5/24/2022 is the committee review and voting time.  
link: https://medium.com/block-science/mapping-the-computer-aided-governance-process-2e47eaf70889
Bounty：80u

**Comment by xinyang309** [comment]
xinyang309 will do the bounty
