### ISSUE TITLE
DAOrayaki |task|  Composability is the Most Powerful Creative Force in the Universe

### ISSUE THREAD

**Issue by asqwasweer** [DAOrayaki/DAOrayaki-Bounty#222]
Title: DAOrayaki | Composability is the Most Powerful Creative Force in the Universe
 Deadline: 5/21/2022  
Committee Decision: 5/22/2022-5/24/2022  
**Description: English to Chinese;** 
5/18/2022-5/21/2022 is the creator's translation time, that is, creators need to submit before 5/12 ;5/22/2022-5/24/2022 is the committee review and voting time.  
link: https://medium.com/building-the-metaverse/composability-is-the-most-powerful-creative-force-in-the-universe-e82e3dd83ccd
Bounty：100u

**Comment by Heyyawn** [comment]
Heyyawn#1025 will do this bounty
