### ISSUE TITLE
DAOrayaki |task|  Byzantine Generals Turn to Quantum

### ISSUE THREAD

**Issue by asqwasweer** [DAOrayaki/DAOrayaki-Bounty#227]
Title: DAOrayaki | Byzantine Generals Turn to Quantum
 Deadline: 5/21/2022  
Committee Decision: 5/22/2022-5/24/2022  
**Description: English to Chinese;**
 5/18/2022-5/21/2022 is the creator's translation time, that is, creators need to submit before 5/12 ;5/22/2022-5/24/2022 is the committee review and voting time.  
link: https://medium.com/geekculture/byzantine-generals-turn-to-quantum-ab81bd938cc2
Bounty：60u

**Comment by susu0929** [comment]
susu0929will do the bounty

**Comment by susu0929** [comment]
skyh#4923will do the bounty

**Comment by Zhixuan0318** [comment]
Tan Zhi Xuan#7032 will like to do this bounty if no submission is made. Position 2.

**Comment by Zhixuan0318** [comment]
@asqwasweer

**Comment by susu0929** [comment]
It's already finished in PR, thank you for the reply.

**Comment by asqwasweer** [comment]
> @asqwasweer

你在discord抢任务时抢到的是第二位的位置。
所以这个任务首先得让抢到第一的人做
