### ISSUE TITLE
DAOrayaki | task| QT/ New qubit platform could transform quantum information science and technology

### ISSUE THREAD

**Issue by asqwasweer** [DAOrayaki/DAOrayaki-Bounty#228]
Title: DAOrayaki | QT/ New qubit platform could transform quantum information science and technology
 Deadline: 5/21/2022  
Committee Decision: 5/22/2022-5/24/2022  
**Description: English to Chinese;** 
5/18/2022-5/21/2022 is the creator's translation time, that is, creators need to submit before 5/12 ;5/22/2022-5/24/2022 is the committee review and voting time.  
link: https://medium.com/paradigm-fund/qt-new-qubit-platform-could-transform-quantum-information-science-and-technology-c6427f96f865
Bounty：150u

**Comment by xinyang309** [comment]
xinyang309 will do the bounty
