### ISSUE TITLE
Exploring the Modularisation of Blockchains: An Introduction to Rollups

### ISSUE THREAD

**Issue by Will-Holden** [DAOrayaki/DAOrayaki-Bounty#23]
类型 : Translation
时间: 7天内
要求: 将链接中的英文文章翻译为中文。
链接: https://medium.com/@bencharlesharvey/exploring-the-modularisation-of-blockchains-an-introduction-to-rollups-42c188ac1a5d
Bounty : 140 U

Type: Translation
Deadline: Within 7 days
Requirement: Translate the English article in the link into Chinese.
Link: https://medium.com/@bencharlesharvey/exploring-the-modularisation-of-blockchains-an-introduction-to-rollups-42c188ac1a5d
Bounty: 140 U

**Comment by thesayraj** [comment]
How to submit the result. In plain text or make some post like exactly on medium or something else.

**Comment by Will-Holden** [comment]
Submit from a share docs, by updating the github record files, to let the daorayaki committee know.

**Comment by Will-Holden** [comment]
> How to submit the result. In plain text or make some post like exactly on medium or something else.

Sorry for not replying in time.
Submit from a share docs, by updating the github record files, to let the daorayaki committee know.

**Comment by icbc1388** [comment]
已完成，链接：https://zhuanlan.zhihu.com/p/453463080
不知如何提交，不知这样算不算？

**Comment by Will-Holden** [comment]
> 已完成，链接：https://zhuanlan.zhihu.com/p/453463080 不知如何提交，不知这样算不算？

您好，目前我们采用智能合约来发布bounty，所以必须通过提交pr来提交答案。如何提交，请参考https://github.com/DAOrayaki/DAOrayaki-Bounty

**Comment by icbc1388** [comment]
#22 #23 #27
