### ISSUE TITLE
DAOrayaki | Is SpaceX’s Raptor engine the king of rocket engines?

### ISSUE THREAD

**Issue by Will-Holden** [DAOrayaki/DAOrayaki-Bounty#29]
类型：翻译
时间：1.7-1.12日翻译；1.13-1.19 委员会review和投票
描述：英译中
链接：https://everydayastronaut.com/raptor-engine/
Bounty：150u

Type: Translation
Deadline: 1.7-1.12 translation; 1.13-1.19 committee review and vote
Requirement: Translate the English article in the link into Chinese.
Link: https://everydayastronaut.com/raptor-engine/
Bounty: 150 U

**Comment by RockyLiii** [comment]
#1 <RockyLiii>

**Comment by Will-Holden** [comment]
Will Holden already take the bounty,
