### ISSUE TITLE
DAOrayaki | bounty| Will Starship and SLS herald a spaceflight revolution?

### ISSUE THREAD

**Issue by asqwasweer** [DAOrayaki/DAOrayaki-Bounty#292]
Title: DAOrayaki | Will Starship and SLS herald a spaceflight revolution?
 Deadline: 6/11/2022  
Committee Decision: 6/12/2022-6/14/2022  
Description: English to Chinese;
 6/8/2022-6/11/2022 is the creator's translation time, that is, creators need to submit before 6/12 ;6/12/2022-6/14/2022 is the committee review and voting time.  
link: https://earthsky.org/space/starship-and-sls-a-spaceflight-revolution-ahead/
Bounty：40u

**Comment by Heyyawn** [comment]
Heyyawn will do this bounty
