### ISSUE TITLE
DAOrayaki | bounty|The Top Ten Ways Space Exploration Benefits Earth

### ISSUE THREAD

**Issue by asqwasweer** [DAOrayaki/DAOrayaki-Bounty#294]
Title: DAOrayaki | The Top Ten Ways Space Exploration Benefits Earth
 Deadline: 6/11/2022  
Committee Decision: 6/12/2022-6/14/2022  
Description: English to Chinese; 6/8/2022-6/11/2022 is the creator's translation time, that is, creators need to submit before 6/12 ;6/12/2022-6/14/2022 is the committee review and voting time.  
link: https://medium.com/the-cosmic-companion/the-top-ten-ways-space-exploration-benefits-earth-feb0029ae612
Bounty：80u

**Comment by Heyyawn** [comment]
Heyyawn will do this bounty
