### ISSUE TITLE
DAOrayaki | bounty| These 4 signs of alien technology could lead us to extraterrestrial life

### ISSUE THREAD

**Issue by asqwasweer** [DAOrayaki/DAOrayaki-Bounty#296]
Title: DAOrayaki | These 4 signs of alien technology could lead us to extraterrestrial life
 Deadline: 6/11/2022  
Committee Decision: 6/12/2022-6/14/2022  
Description: English to Chinese; 6/8/2022-6/11/2022 is the creator's translation time, that is, creators need to submit before 6/12 ;6/12/2022-6/14/2022 is the committee review and voting time.  
link: https://www.sciencefocus.com/space/signs-of-alien-tech/
Bounty：40u

**Comment by susu0929** [comment]
skyh#4923 will do the bounty

**Comment by JohnnyJiangY** [comment]
cool
