### ISSUE TITLE
DAOrayaki | Quantum full-stack libraries

### ISSUE THREAD

**Issue by Will-Holden** [DAOrayaki/DAOrayaki-Bounty#30]
类型：翻译
时间：1.7-1.10日翻译；1.11-1.17 委员会review和投票
描述：英译中；文章中的超链接也需要在翻译的文章中呈现，不可省略。
链接：https://qosf.org/project_list/
Bounty：70u

Type: Translation
Deadline: 1.1-1.10 translation; 1.11-1.17 committee review and voting
Requirement: Translate the English article in the link into Chinese; hyperlinks in the article also need to be presented in the translated article
Link: https://qosf.org/project_list/
Bounty: 70 U

**Comment by depth-first** [comment]
#1 @depthfirst

**Comment by Will-Holden** [comment]
Hi depth-first, the bounty has released, please check u wallet
