### ISSUE TITLE
DAOrayaki | Engine Cooling – Why Rocket Engines Don’t Melt

### ISSUE THREAD

**Issue by Will-Holden** [DAOrayaki/DAOrayaki-Bounty#34]
类型：翻译
时间：1/18/2022-1/23/2022
Review 时间：1/24/2022-1/28/2022
描述：英译中；1.18-1.23为创作者翻译时间，即创者者需要在1.23号之前提交；1.24-1.28为委员会审核及投票时间。
链接：https://everydayastronaut.com/engine-cooling-methodes/
Bounty：110u

Type: Translation
Deadline: 1/18/2022-1/23/2022
Committee Decision: 1/24/2022-1/28/2022
Requirement: Translate the English article in the link into Chinese; 1.18-1.23 is the translation time for creators, that is, creators need to submit before 1.23; 1.24-1.28 is the review committee and voting time.
Link: https://everydayastronaut.com/engine-cooling-methodes/
Bounty: 110U

**Comment by tw23** [comment]
<tw23> will do this bounty

**Comment by xinyang309** [comment]
xinyang309 will do this bounty.
