### ISSUE TITLE
DAOrayaki | How SpaceX and Boeing will get Astronauts to the ISS. A comparison of the Crew Dragon, Starliner, Soyuz and Space Shuttle.

### ISSUE THREAD

**Issue by Will-Holden** [DAOrayaki/DAOrayaki-Bounty#38]
类型：翻译
翻译时间：1/23/2022-1/27/2022
Review 时间：1/28/2022-1/31/2022
描述：英译中；1.23-1.27为创作者翻译时间，即创者者需要在1.27号之前提交；1.28-1.31为委员会审核及投票时间。
链接：https://everydayastronaut.com/crew-dragon-vs-starliner/
Bounty：130u

Type: Translation
Deadline: 1/23/2022-1/27/2022
Committee Decision: 1/28/2022-1/31/2022
Description: English to Chinese; 1.23-1.27 iis the translation time for creators, that is, creators need to submit before 1.27; 1.28-1.31 is the committee review and voting time.
Link: https://everydayastronaut.com/crew-dragon-vs-starliner/
Bounty: 130u

**Comment by hahaho1** [comment]
hahaho will do this bounty
