### ISSUE TITLE
DAOrayaki | Ion Propulsion: Farther, Faster, Cheaper

### ISSUE THREAD

**Issue by Will-Holden** [DAOrayaki/DAOrayaki-Bounty#40]
类型：翻译
翻译时间：1/23/2022-1/27/2022
Review 时间：1/28/2022-1/31/2022
描述：英译中；1.23-1.27为创作者翻译时间，即创者者需要在1.27号之前提交；1.28-1.31为委员会审核及投票时间。
链接：https://www.nasa.gov/centers/glenn/technology/Ion_Propulsion1.html
Bounty：80u

Type: Translation
Deadline: 1/23/2022-1/27/2022
Committee Decision: 1/28/2022-1/31/2022
Description: English to Chinese; 1.23-1.27 is the translation time for creators, that is, creators need to submit before 1.27; 1.28-1.31 is the committee review and voting time.
Link: https://www.nasa.gov/centers/glenn/technology/Ion_Propulsion1.html
Bounty: 80u

**Comment by ShaunTime** [comment]
<ShaunTime>  will do this bounty

**Comment by ShaunTime** [comment]
Hi Will，
I have synced the translated Chinese document online, what should I do next?

**Comment by Will-Holden** [comment]
Hi, ShaunTime, please make sure that u hackerlink account is bind with your github account and wallet address. Our committee will review your result.

**Comment by ShaunTime** [comment]
> Hi, ShaunTime, please make sure that u hackerlink account is bind with your github account and wallet address. Our committee will review your result.

Hi,Will, Confirmed~：）
