### ISSUE TITLE
DAOrayaki | MOLOCHDAO ANNUAL REPORT 2021

### ISSUE THREAD

**Issue by Will-Holden** [DAOrayaki/DAOrayaki-Bounty#50]
类型：翻译
翻译时间：2/22/2022-2/23/2022
Review 时间：2/24/2022-/27/2022
描述：英译中；2/22-2/23为创作者翻译时间，即创作者需要在2.23号之前提交；2.24-2.27 为委员会审核及投票时间。
链接：https://molochdao.com/annual-report/
Bounty：100u

Type: Translation
DeadLine: 2/22/2022-2/23/2022
Committee Decision: 2/24/2022-/27/2022
Description: English to Chinese;2/22-2/23 is the creator's translation time, that is, creators need to submit before 2.23; 2.24-2.27 is the committee review and voting time.
Link: https://molochdao.com/annual-report/
Bounty: 100u

**Comment by tw23** [comment]
Shaytan#0977 will do this bounty
