### ISSUE TITLE
DAOrayaki | Decentralized Identity: Passport to Web3

### ISSUE THREAD

**Issue by Will-Holden** [DAOrayaki/DAOrayaki-Bounty#51]
类型：翻译
翻译时间：2/22/2022-2/23/2022
Review 时间：2/24/2022-/27/2022
描述：英译中；2/22-2/23为创作者翻译时间，即创作者需要在2.23号之前提交；2.24-2.27为委员会审核及投票时间。
链接：https://medium.com/amber-group/decentralized-identity-passport-to-web3-d3373479268a
Bounty：110u

Type: Translation
DeadLine: 2/22/2022-2/23/2022
Committee Decision: 2/24/2022-/27/2022
Description: English to Chinese;2/22-2/23 is the creator's translation time, that is, creators need to submit before 2.23; 2.24-2.27 is the committee review and voting time.
Link: https://medium.com/amber-group/decentralized-identity-passport-to-web3-d3373479268a
Bounty: 110u

**Comment by hahaho1** [comment]
hahaho will do this bounty.
