### ISSUE TITLE
DAOrayaki | QT/ Quantum computing in silicon hits 99 percent accuracy

### ISSUE THREAD

**Issue by Will-Holden** [DAOrayaki/DAOrayaki-Bounty#52]
类型：翻译
翻译时间：2/22/2022-2/23/2022
Review 时间：2/24/2022-/27/2022
描述：英译中；2/22-2/23为创作者翻译时间，即创作者需要在2.23号之前提交；2.24-2.27为委员会审核及投票时间。
链接：https://medium.com/paradigm-fund/qt-quantum-computing-in-silicon-hits-99-percent-accuracy-684ee26cfbf8
Bounty：130u

Type: Translation
DeadLine: 2/22/2022-2/23/2022
Committee Decision: 2/24/2022-/27/2022
Description: English to Chinese;2/22-2/23 is the creator's translation time, that is, creators need to submit before 2.23; 2.24-2.27 is the committee review and voting time.
Link: https://medium.com/paradigm-fund/qt-quantum-computing-in-silicon-hits-99-percent-accuracy-684ee26cfbf8
Bounty: 130u

**Comment by tw23** [comment]
Shaytan#0977 will do this bounty

**Comment by Will-Holden** [comment]
Will Holden will do this bounty

**Comment by Will-Holden** [comment]
Will Holden will do this bounty

**Comment by Will-Holden** [comment]
Will Holden will do this bounty
