### ISSUE TITLE
DAOrayaki | Article Review | Decentralized Identity: Passport to Web3

### ISSUE THREAD

**Issue by Will-Holden** [DAOrayaki/DAOrayaki-Bounty#57]
类型：文章审核
截止日期：2/23/2022-2/24/2022
评论文章链接：https://docs.google.com/document/d/1sqOqbR8D3kdcwk-VpOYo5qXEjeQA3hYQgKtXcb7iifg/edit
原文链接：https://medium.com/amber-group/decentralized-identity-passport-to-web3-d3373479268a
审核标准及要求：
https://imported-honesty-ae4.notion.site/Review-Translation-Article-Standard-e3182fbeaa714be28ea4e87e963ebdf0
赏金：11u

Type: Article Review
DeadLine: 2/23/2022-2/24/2022
Review article Link: https://docs.google.com/document/d/1sqOqbR8D3kdcwk-VpOYo5qXEjeQA3hYQgKtXcb7iifg/edit
Original article link：https://medium.com/amber-group/decentralized-identity-passport-to-web3-d3373479268a
Review standards and Requirements：
https://imported-honesty-ae4.notion.site/Review-Translation-Article-Standard-e3182fbeaa714be28ea4e87e963ebdf0
Bounty：11u

**Comment by xinyang309** [comment]
xinyang309 will do this bounty.
