### ISSUE TITLE
DAOrayaki Giveaways| Article Review | PROOF OF STEAK: BUILDING A COMMUNITY-DRIVEN FOOD INDUSTRY WITH WEB3  

### ISSUE THREAD

**Issue by Will-Holden** [DAOrayaki/DAOrayaki-Bounty#58]
类型：文章审核
截止日期：2/23/2022-2/24/2022
评论文章链接：
https://docs.google.com/document/d/1lVarq_UFpel0goQt_z826cFQ2zL3TgZrWUSI4Nc7VY0/edit
原文链接： https://www.fwb.help/wip/proof-of-steak
审核标准及要求：
https://imported-honesty-ae4.notion.site/Review-Translation-Article-Standard-e3182fbeaa714be28ea4e87e963ebdf0
赏金：9u

Type: Article Review 
DeadLine: 2/23/2022-2/24/2022
Review article Link:
 https://docs.google.com/document/d/1lVarq_UFpel0goQt_z826cFQ2zL3TgZrWUSI4Nc7VY0/edit
Original article link： https://www.fwb.help/wip/proof-of-steak
Review standard and Requirements：
https://imported-honesty-ae4.notion.site/Review-Translation-Article-Standard-e3182fbeaa714be28ea4e87e963ebdf0
Bounty: 9u

**Comment by ShaunTime** [comment]
Closed #61
