### ISSUE TITLE
DAOrayaki | Article Review | MOLOCHDAO ANNUAL REPORT 2021

### ISSUE THREAD

**Issue by Will-Holden** [DAOrayaki/DAOrayaki-Bounty#63]
类型：评论文章
截止日期：2/24/2022-2/25/2022
评论文章链接：https://docs.google.com/document/d/1rjTwm4Ludr8cnIkX8C7x6d0b_jNkxG4ZwjK5DqzLiyk/edit
原文链接： https://molochdao.com/annual-report/
审核标准及要求：
https://imported-honesty-ae4.notion.site/Review-Translation-Article-Standard-e3182fbeaa714be28ea4e87e963ebdf0
赏金：10u

Type: Article Review
DeadLine: 2/24/2022-2/25/2022
Review article Link: 
https://docs.google.com/document/d/1rjTwm4Ludr8cnIkX8C7x6d0b_jNkxG4ZwjK5DqzLiyk/edit
Original article link：  https://molochdao.com/annual-report/
Review standards and Requirements：
https://imported-honesty-ae4.notion.site/Review-Translation-Article-Standard-e3182fbeaa714be28ea4e87e963ebdf0
Bounty: 10u

**Comment by joincc** [comment]
The translation is accurate, the expression is very clear, and the mistakes are in 1-3 places;

This article should be voted through;
