### ISSUE TITLE
#62 Update DAORayaki Giveaway | Article Review | 2022-2-23

### ISSUE THREAD

**Issue by jefflee147** [DAOrayaki/DAOrayaki-Bounty#66]
#62 Article Review | How Crypto Can Regenerate the World #62

-https://docs.google.com/document/d/1dKDc30LTJ1VjQHvzUxP772gam2b75so7gMomxoIxTk8/edit#
- 贡献者： （too lee#1302   feiyanggan@gmail.com   bsc address: 0x07aE03eD4b39938552bb02F3A8563Bef3E03856A）

**Comment by Will-Holden** [comment]
This is a mistake
