### ISSUE TITLE
DAOrayaki Bounty| Task | QT/ Quantum Computing explained! 

### ISSUE THREAD

**Issue by Will-Holden** [DAOrayaki/DAOrayaki-Bounty#69]
类型：翻译
翻译时间：3/1/2022-3/3/2022 
Review 时间 : 3/4/2022-/7/2022 
描述：英译中；3/1/2022-3/3/2022为创作者翻译时间，即创作者需要在3.3号之前提交；3/4/2022-3/7/2022为委员会审核及投票时间。
链接：https://towardsdatascience.com/quantum-computing-explained-a114999299ca 
Bounty：110u

Type: Translation 
DeadLine: 3/1/2022-3/3/2022 
Committee Decision: 3/4/2022-/7/2022 
Description: English to Chinese;3/1/2022-3/3/2022 is the creator's translation time, that is, creators need to submit before 3/3 ; 3/4/2022-3/7/2022 is the committee review and voting time. 
Link: https://towardsdatascience.com/quantum-computing-explained-a114999299ca 
Bounty: 110u

**Comment by tw23** [comment]
shaytan#0977 will do this bounty

**Comment by Will-Holden** [comment]
Will Holden will do this bounty
