### ISSUE TITLE
DAOrayaki Bounty| Task | QT/ Quantum Cryptography vs Post-Quantum Cryptography

### ISSUE THREAD

**Issue by Will-Holden** [DAOrayaki/DAOrayaki-Bounty#73]
类型：翻译
翻译时间： 3/2/2022-3/5/2022
Review 时间：3/5/2022-3/7/2022
描述：英译中；3/5/2022-3/7/2022为创作者翻译时间，即创作者需要在3.5号之前提交；3/5/2022-3/7/2022为委员会审核及投票时间。
链接：https://medium.com/swlh/quantum-cryptography-vs-post-quantum-cryptography-c769429cb06f
Bounty：40u

Type: Translation
DeadLine: 3/2/2022-3/5/2022
Committee Decision: 3/5/2022-3/7/2022
Description: English to Chinese;3/2/2022-3/5/2022 is the creator's translation time, that is, creators need to submit before 3/5 ; 3/5/2022-3/7/2022 is the committee review and voting time.
Link: https://medium.com/swlh/quantum-cryptography-vs-post-quantum-cryptography-c769429cb06f
Bounty: 40u

**Comment by xinyang309** [comment]
xinyang309 will do the bounty.
