### ISSUE TITLE
DAOrayaki Bounty| Task | QT/ Learn Quantum Computing With These Seven Projects

### ISSUE THREAD

**Issue by Will-Holden** [DAOrayaki/DAOrayaki-Bounty#75]
类型：翻译
翻译时间： 3/2/2022-3/5/2022
Review 时间：3/5/2022-3/7/2022
描述：英译中；3/2/2022-3/5/2022为创作者翻译时间，即创作者需要在3.5号之前提交；3/5/2022-3/7/2022为委员会审核及投票时间。
链接：https://medium.com/qiskit/learn-quantum-computing-with-these-seven-projects-7478d90d125a
Bounty：50u

Type: Translation
DeadLine: 3/2/2022-3/5/2022
Committee Decision: 3/5/2022-3/7/2022
Description: English to Chinese;3/2/2022-3/5/2022 is the creator's translation time, that is, creators need to submit before 3/5 ; 3/5/2022-3/7/2022 is the committee review and voting time.
Link: https://medium.com/qiskit/learn-quantum-computing-with-these-seven-projects-7478d90d125a
Bounty: 50u

**Comment by hahaho1** [comment]
hahaho will do this bounty.
