### ISSUE TITLE
 DAOrayaki  Giveaway | Task |  SP/ Colonizing Mars may require humanity to tweak its DNA

### ISSUE THREAD

**Issue by Will-Holden** [DAOrayaki/DAOrayaki-Bounty#89]
Title: DAOrayaki  Giveaway | Task |  SP/ Colonizing Mars may require humanity to tweak its DNA
类型: Translation(including community sharing)
截止日期: 3/8/2022-3/11/2022
委员会审核: 3/11/2022-3/13/2022
要求:英译中； 3/8/2022-3/11/2022为创作者翻译时间，即创作者需要在3/11/2022号之前提交； 3/11/2022 -3/13/2022为委员会审核及投票时间。
链接:https://www.space.com/mars-colony-human-genetic-engineering-tardigrades.html
赏金: 30u

Title: DAOrayaki  Giveaway | Task |  SP/ Colonizing Mars may require humanity to tweak its DNA
Type: Translation(including community sharing)
Deadline: 3/8/2022-3/11/2022
Committee Decision: 3/11/2022-3/13/2022
Description: English to Chinese;3/8/2022-3/11/2022 is the creator's translation time, that is, creators need to submit before 3/11 ; 3/11/2022-3/13/2022 is the committee review and voting time.
Link:https://www.space.com/mars-colony-human-genetic-engineering-tardigrades.html
Bounty: 30u

**Comment by hahaho1** [comment]
hahaho will do this bounty.
