### ISSUE TITLE
 DAOrayaki  Giveaway | Task |  SP/ Mars missions: A brief history

### ISSUE THREAD

**Issue by Will-Holden** [DAOrayaki/DAOrayaki-Bounty#91]
Title: DAOrayaki  Giveaway | Task |  SP/ Mars missions: A brief history
类型: Translation(including community sharing and two figures in the article, link is as following the article link)
截止日期: 3/8/2022-3/11/2022
委员会审核: 3/11/2022-3/13/2022
要求:英译中； 3/8/2022-3/11/2022为创作者翻译时间，即创作者需要在3/11/2022号之前提交； 3/11/2022 -3/13/2022为委员会审核及投票时间。
链接:https://www.space.com/13558-historic-mars-missions.html
https://cdn.mos.cms.futurecdn.net/ufs3Rg5LRjL2bjMW54YL5H.png:
https://cdn.mos.cms.futurecdn.net/QXXMQVVFMbn4JoebL2Qxkg.png:
赏金: 90 USDC

Title: DAOrayaki  Giveaway | Task |  SP/ Mars missions: A brief history
Type: Translation(including community sharing and two figures in the article, link is as following the article link)
Deadline: 3/8/2022-3/11/2022
Committee Decision: 3/11/2022-3/13/2022
Description: English to Chinese;3/8/2022-3/11/2022 is the creator's translation time, that is, creators need to submit before 3/11 ; 3/11/2022-3/13/2022 is the committee review and voting time.
Link:https://www.space.com/13558-historic-mars-missions.html
https://cdn.mos.cms.futurecdn.net/ufs3Rg5LRjL2bjMW54YL5H.png:
https://cdn.mos.cms.futurecdn.net/QXXMQVVFMbn4JoebL2Qxkg.png:
Bounty: 90 USDC

**Comment by xinyang309** [comment]
xinyang309 will do the bounty.

**Comment by whale49** [comment]
....
