### ISSUE TITLE
 DAOrayaki  Bounty | Task |  The Fundamental Problems With Play-to-Earn Games, And How To Solve Them

### ISSUE THREAD

**Issue by Will-Holden** [DAOrayaki/DAOrayaki-Bounty#97]
Title: DAOrayaki  Giveaway | Task |  The Fundamental Problems With Play-to-Earn Games, And How To Solve Them
类型: Translation
截止日期: 3/12/2022-3/13/2022
委员会审核: 3/14/2022-3/15/2022
要求:英译中；3/12/2022-3/13/2022为创作者翻译时间，即创作者需要在3/13号之前提交； 3/14/2022 -3/15/2022为委员会审核及投票时间。
原文链接: https://medium.com/@theo/the-fundamental-problems-with-play-to-earn-games-and-how-to-solve-them-dd243033643
赏金:50USDC

Title: DAOrayaki  Giveaway | Task | The Fundamental Problems With Play-to-Earn Games, And How To Solve Them
Type: Translation
Deadline: 3/12/2022-3/13/2022
Committee Decision: 3/14/2022-3/15/2022
Description: English to Chinese;3/12/2022-3/13/2022 is the creator's translation time, that is, creators need to submit before 3/13 ; 3/14/2022-3/15/2022 is the committee review and voting time.
Link: https://medium.com/@theo/the-fundamental-problems-with-play-to-earn-games-and-how-to-solve-them-dd243033643
Bounty:50USDC

**Comment by ShaunTime** [comment]
Shaun will do this Giveaway.

**Comment by GuassianDist** [comment]
new here, can do this giveaway but don't the process

**Comment by Will-Holden** [comment]
> new here, can do this giveaway but don't know the exact process

Hellow, GuassianDist, U can check our readme and follow the rules. The task is released on discord.
